version: 2
jobs:
  test:
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - run:
        name: "Pull Submodules"
        command: |
          git submodule init
          git submodule update
    - run:
        name: Install
        command: |
          sudo apt-get update
          sudo apt-get install -yq build-essential gcc g++ make bison flex libpthread-stubs0-dev cmake
    - run:
        name: Get g++ version
        command: g++ --version
    - run:
        name: Run tests
        command: |
          cmake -G 'Unix Makefiles'
          make -j2
          ./pbrt_test
workflows:
  version: 2
  test:
    jobs:
    - test